<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Trivy Security Dashboard</title>
  <style>
    :root {
      --bg-color: #f0f2f5;
      --card-bg: #ffffff;
      --text-color: #333;
      --critical: #dc3545;
      --high: #fd7e14;
      --medium: #ffc107;
      --low: #0d6efd;
      --safe: #198754;
    }
    body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 30px; background-color: var(--bg-color); color: var(--text-color); }

    /* Header */
    .header { text-align: center; margin-bottom: 40px; }
    h1 { color: #2c3e50; margin: 0; font-size: 2.5em; }
    p.subtitle { color: #666; margin-top: 10px; }

    /* Dashboard Cards */
    .dashboard-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; max-width: 1200px; margin-left: auto; margin-right: auto; }
    .card { background: var(--card-bg); padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); text-align: center; transition: transform 0.2s; border-bottom: 4px solid transparent; }
    .card:hover { transform: translateY(-5px); }
    .card h3 { margin: 0; font-size: 3em; font-weight: 800; }
    .card span { font-size: 1em; color: #777; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }

    /* Color Modifiers */
    .card.critical { border-color: var(--critical); } .card.critical h3 { color: var(--critical); }
    .card.high { border-color: var(--high); } .card.high h3 { color: var(--high); }
    .card.medium { border-color: var(--medium); } .card.medium h3 { color: var(--medium); }
    .card.low { border-color: var(--low); } .card.low h3 { color: var(--low); }
    .card.total { border-color: #6c757d; } .card.total h3 { color: #2c3e50; }

    /* Detailed Section */
    .container { max-width: 1200px; margin: 0 auto; }
    .target-section { background: var(--card-bg); padding: 25px; margin-bottom: 25px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    .target-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #f0f0f0; padding-bottom: 15px; margin-bottom: 15px; }
    .target-title { font-size: 1.2em; font-weight: bold; color: #34495e; display: flex; align-items: center; gap: 10px; }
    .target-type { font-size: 0.8em; background: #e9ecef; padding: 4px 8px; border-radius: 4px; color: #495057; }

    /* Table */
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th { background-color: #f8f9fa; text-align: left; padding: 15px; border-bottom: 2px solid #dee2e6; color: #495057; font-size: 0.9em; text-transform: uppercase; }
    td { padding: 15px; border-bottom: 1px solid #eee; vertical-align: top; font-size: 0.95em; }
    tr:last-child td { border-bottom: none; }
    tr:hover { background-color: #f8f9fa; }

    /* Badges & Links */
    .badge { padding: 6px 12px; border-radius: 20px; color: white; font-weight: bold; font-size: 0.8em; display: inline-block; min-width: 60px; text-align: center; }
    .bg-CRITICAL { background-color: var(--critical); }
    .bg-HIGH { background-color: var(--high); }
    .bg-MEDIUM { background-color: var(--medium); color: #333; }
    .bg-LOW { background-color: var(--low); }

    .vuln-id { font-family: 'Consolas', monospace; color: #0d6efd; font-weight: bold; }
    .links a { color: #0d6efd; text-decoration: none; font-weight: 500; font-size: 0.9em; border: 1px solid #0d6efd; padding: 4px 10px; border-radius: 4px; transition: all 0.2s; }
    .links a:hover { background-color: #0d6efd; color: white; }

    .safe-message { text-align: center; color: var(--safe); padding: 30px; font-size: 1.1em; font-weight: 500; }
  </style>
</head>
<body>

  <div class="header">
    <h1>🛡️ Security Scan Report</h1>
    <p class="subtitle">Generated by Trivy via GitHub Actions</p>
  </div>

  <div class="dashboard-grid">
    <div class="card total">
      <h3 id="count-targets">0</h3>
      <span>Scanned Modules</span>
    </div>
    <div class="card critical">
      <h3 id="count-critical">0</h3>
      <span>Critical</span>
    </div>
    <div class="card high">
      <h3 id="count-high">0</h3>
      <span>High</span>
    </div>
    <div class="card medium">
      <h3 id="count-medium">0</h3>
      <span>Medium</span>
    </div>
    <div class="card low">
      <h3 id="count-low">0</h3>
      <span>Low</span>
    </div>
  </div>

  <div class="container">
    {{ range . }}
    <div class="target-section">
      <div class="target-header">
        <div class="target-title">
          <span>📂 {{ .Target }}</span>
          <span class="target-type">{{ .Type }}</span>
        </div>
      </div>

      {{ if (or .Vulnerabilities .Misconfigurations) }}
      <table>
        <thead>
          <tr>
            <th style="width: 100px;">Severity</th>
            <th style="width: 180px;">ID</th>
            <th>Package / Resource</th>
            <th>Description</th>
            <th style="width: 140px;">Action</th>
          </tr>
        </thead>
        <tbody>
          {{ range .Vulnerabilities }}
          <tr class="issue-row" data-severity="{{ .Severity }}">
            <td><span class="badge bg-{{ .Severity }}">{{ .Severity }}</span></td>
            <td class="vuln-id">{{ .VulnerabilityID }}</td>
            <td>{{ .PkgName }}<br><small style="color:#888">{{ .InstalledVersion }}</small></td>
            <td><b>{{ .Title }}</b><br><span style="color:#555; font-size:0.9em">{{ .Description }}</span></td>
            <td><div class="links">{{ if .PrimaryURL }}<a href="{{ .PrimaryURL }}" target="_blank">Fix Info</a>{{ else }}-{{ end }}</div></td>
          </tr>
          {{ end }}

          {{ range .Misconfigurations }}
          <tr class="issue-row" data-severity="{{ .Severity }}">
            <td><span class="badge bg-{{ .Severity }}">{{ .Severity }}</span></td>
            <td class="vuln-id">{{ .ID }}</td>
            <td>{{ .Title }}</td>
            <td><b>{{ .Message }}</b></td>
            <td><div class="links"><a href="{{ .PrimaryURL }}" target="_blank">Remediation</a></div></td>
          </tr>
          {{ end }}
        </tbody>
      </table>
      {{ else }}
        <div class="safe-message">
          ✅ No security issues found in this module.
        </div>
      {{ end }}
    </div>
    {{ end }}
  </div>

  <script>
    // Simple logic to count the rows and update dashboard
    document.addEventListener('DOMContentLoaded', function() {
      // 1. Count Targets (Scanned Modules)
      const targets = document.querySelectorAll('.target-section');
      document.getElementById('count-targets').textContent = targets.length;

      // 2. Count Severities
      let critical = 0, high = 0, medium = 0, low = 0;

      const rows = document.querySelectorAll('.issue-row');
      rows.forEach(row => {
        const severity = row.getAttribute('data-severity');
        if (severity === 'CRITICAL') critical++;
        else if (severity === 'HIGH') high++;
        else if (severity === 'MEDIUM') medium++;
        else if (severity === 'LOW') low++;
      });

      // 3. Update UI with Animation
      function animateValue(id, start, end, duration) {
        if (start === end) return;
        const obj = document.getElementById(id);
        let startTimestamp = null;
        const step = (timestamp) => {
          if (!startTimestamp) startTimestamp = timestamp;
          const progress = Math.min((timestamp - startTimestamp) / duration, 1);
          obj.innerHTML = Math.floor(progress * (end - start) + start);
          if (progress < 1) {
            window.requestAnimationFrame(step);
          }
        };
        window.requestAnimationFrame(step);
      }

      animateValue("count-critical", 0, critical, 1000);
      animateValue("count-high", 0, high, 1000);
      animateValue("count-medium", 0, medium, 1000);
      animateValue("count-low", 0, low, 1000);
    });
  </script>
</body>
</html>
