<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Trivy Security Report</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f4f6f9; color: #333; }
    h1 { color: #2c3e50; text-align: center; }
    .summary { display: flex; justify-content: center; gap: 20px; margin-bottom: 30px; }
    .card { background: white; padding: 15px 25px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); text-align: center; min-width: 100px; }
    .card h3 { margin: 0; font-size: 2em; }
    .card span { font-size: 0.9em; color: #777; }
    .CRITICAL { color: #e74c3c; border-top: 4px solid #e74c3c; }
    .HIGH { color: #e67e22; border-top: 4px solid #e67e22; }
    .MEDIUM { color: #f1c40f; border-top: 4px solid #f1c40f; }
    .LOW { color: #3498db; border-top: 4px solid #3498db; }

    .target-section { background: white; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
    .target-title { font-size: 1.2em; font-weight: bold; margin-bottom: 15px; color: #34495e; border-bottom: 2px solid #eee; padding-bottom: 10px; }

    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th { background-color: #f8f9fa; text-align: left; padding: 12px; border-bottom: 2px solid #ddd; color: #555; }
    td { padding: 12px; border-bottom: 1px solid #eee; vertical-align: top; }
    tr:hover { background-color: #fafafa; }

    .badge { padding: 4px 8px; border-radius: 4px; color: white; font-weight: bold; font-size: 0.8em; }
    .bg-CRITICAL { background-color: #e74c3c; }
    .bg-HIGH { background-color: #e67e22; }
    .bg-MEDIUM { background-color: #f1c40f; color: #333; }
    .bg-LOW { background-color: #3498db; }
    .bg-UNKNOWN { background-color: #95a5a6; }

    .vuln-id { font-family: monospace; font-weight: bold; color: #2980b9; }
    .links a { color: #3498db; text-decoration: none; font-size: 0.9em; }
    .links a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>🛡️ Trivy Security Report</h1>

  <div class="summary">
    <div class="card CRITICAL">
      <h3>{{ .Results | len }}</h3>
      <span>Targets</span>
    </div>
  </div>

  {{ range .Results }}
  <div class="target-section">
    <div class="target-title">📂 {{ .Target }} ({{ .Type }})</div>

    {{ if (or .Vulnerabilities .Misconfigurations) }}
    <table>
      <thead>
        <tr>
          <th style="width: 100px;">Severity</th>
          <th style="width: 150px;">ID</th>
          <th>Package / Resource</th>
          <th>Title & Description</th>
          <th style="width: 120px;">Fix Version</th>
        </tr>
      </thead>
      <tbody>
        {{ range .Vulnerabilities }}
        <tr>
          <td><span class="badge bg-{{ .Severity }}">{{ .Severity }}</span></td>
          <td class="vuln-id">{{ .VulnerabilityID }}</td>
          <td>{{ .PkgName }}<br><small>{{ .InstalledVersion }}</small></td>
          <td><b>{{ .Title }}</b><br>{{ .Description }}</td>
          <td>{{ .FixedVersion }}</td>
        </tr>
        {{ end }}

        {{ range .Misconfigurations }}
        <tr>
          <td><span class="badge bg-{{ .Severity }}">{{ .Severity }}</span></td>
          <td class="vuln-id">{{ .ID }}</td>
          <td>{{ .Title }}</td>
          <td>
            <b>{{ .Message }}</b><br>
            <div class="links">
              <a href="{{ .PrimaryURL }}" target="_blank">View Remediation ↗</a>
            </div>
          </td>
          <td>-</td>
        </tr>
        {{ end }}
      </tbody>
    </table>
    {{ else }}
      <p style="color: #27ae60; text-align: center; padding: 20px;">✅ No Vulnerabilities found!</p>
    {{ end }}
  </div>
  {{ end }}

  <p style="text-align: center; color: #999; font-size: 0.8em;">Generated by Trivy via GitHub Actions</p>
</body>
</html>
