name: Cost Analysis

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pull-requests: write # 必須有，Infracost 才能在 PR 留言

jobs:
  cost-estimation-pr:
    name: PR Cost
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    steps:
      - name: Install Infracost CLI
        env:
          INFRACOST_VERSION: v0.10.44
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh -s -- -b /usr/local/bin
          infracost --version

      - name: Set PR Cost Report Date
        id: pr_report_date
        run: echo "value=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

      - name: Checkout base branch
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.base.ref }}"

      - name: Generate Baseline Cost
        run: |
          infracost breakdown --path aws-tf \
                              --show-skipped \
                              --format json \
                              --out-file /tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v5

      - name: Generate Cost Diff
        run: |
          infracost diff --path aws-tf \
                         --show-skipped \
                         --format json \
                         --compare-to /tmp/infracost-base.json \
                         --out-file infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.json

      - name: Show Cost Table in Console
        run: infracost output --path infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.json --format table

      - name: Post Infracost Comment
        run: |
          infracost comment github --path infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --github-token ${{ github.token }} \
                                   --pull-request ${{ github.event.pull_request.number }} \
                                   --behavior update

      - name: Generate Cost HTML Report
        run: infracost output --path infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.json --format html --out-file infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.html

      - name: Upload Cost Report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: infracost-report-pr (${{ steps.pr_report_date.outputs.value }})
          path: |
            infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.html
            infracost-report-pr-${{ steps.pr_report_date.outputs.value }}.json
          retention-days: 60

  cost-estimation-main:
    name: Main Cost
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Install Infracost CLI
        env:
          INFRACOST_VERSION: v0.10.44
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh -s -- -b /usr/local/bin
          infracost --version

      - name: Set Main Cost Report Date
        id: main_report_date
        run: echo "value=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

      - name: Run Infracost Breakdown
        run: |
          infracost breakdown --path aws-tf \
                              --show-skipped \
                              --format json \
                              --out-file infracost-report-main-${{ steps.main_report_date.outputs.value }}.json

      - name: Show Cost Table in Console
        run: |
          infracost output --path infracost-report-main-${{ steps.main_report_date.outputs.value }}.json --format table

      - name: Generate HTML Report
        run: |
          infracost output --path infracost-report-main-${{ steps.main_report_date.outputs.value }}.json --format html --out-file infracost-report-main-${{ steps.main_report_date.outputs.value }}.html

      - name: Upload Cost Report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: infracost-report-main (${{ steps.main_report_date.outputs.value }})
          path: |
            infracost-report-main-${{ steps.main_report_date.outputs.value }}.html
            infracost-report-main-${{ steps.main_report_date.outputs.value }}.json
          retention-days: 60
